networks:
  services_default:
    external: true
services:
  come-in-and-find-out:
    build:
      args:
        NAME: come-in-and-find-out
        TOKEN: $APP_CLIENTS_CIAFO_TOKEN
    container_name: come-in-and-find-out
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`come-in-and-find-out.ch`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  duckumbrella:
    build:
      args:
        NAME: duckumbrella
    container_name: duckumbrella
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`duckumbrella.net`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  gaiapeeps:
    build:
      args:
        NAME: gaiapeeps
        TOKEN: $APP_CLIENTS_PEEPS_TOKEN
    container_name: gaiapeeps
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`gaiapeeps.com`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  igli:
    build:
      args:
        NAME: igli
    container_name: igli
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`igli.info`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  outsideworx:
    build:
      args:
        NAME: outsideworx
    container_name: outsideworx
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`outsideworx.net`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  soupart:
    build:
      args:
        NAME: soupart
        TOKEN: $APP_CLIENTS_SOUP_TOKEN
    container_name: soupart
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`soupart.net`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  soupkitchen:
    build:
      args:
        NAME: soupkitchen
    container_name: soupkitchen
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`soupkitchen.info`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.ntfy.loadbalancer.server.port=81
    networks:
      - services_default
    restart: unless-stopped
  thegreen:
    build:
      args:
        NAME: thegreen
    container_name: thegreen
    networks:
      - services_default
    restart: unless-stopped