networks:
  outsideworx:
    external: true
services:
  come-in-and-find-out:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.come-in-and-find-out.entrypoints=websecure
        - traefik.http.routers.come-in-and-find-out.rule=Host(`come-in-and-find-out.ch`)
        - traefik.http.routers.come-in-and-find-out.tls.certresolver=letsencrypt
        - traefik.http.services.come-in-and-find-out.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.come-in-and-find-out.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.come-in-and-find-out.loadbalancer.server.port=80
    environment:
      TOKEN: $APP_CLIENTS_CIAFO_TOKEN
    image: ghcr.io/outsideworx/come-in-and-find-out:latest
    networks:
      - outsideworx
  duckumbrella:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.duckumbrella.entrypoints=websecure
        - traefik.http.routers.duckumbrella.rule=Host(`duckumbrella.net`)
        - traefik.http.routers.duckumbrella.tls.certresolver=letsencrypt
        - traefik.http.services.duckumbrella.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.duckumbrella.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.duckumbrella.loadbalancer.server.port=80
    image: ghcr.io/outsideworx/duckumbrella:latest
    networks:
      - outsideworx
  gaiapeeps:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gaiapeeps.entrypoints=websecure
        - traefik.http.routers.gaiapeeps.rule=Host(`gaiapeeps.com`)
        - traefik.http.routers.gaiapeeps.tls.certresolver=letsencrypt
        - traefik.http.services.gaiapeeps.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.gaiapeeps.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.gaiapeeps.loadbalancer.server.port=80
    environment:
      TOKEN: $APP_CLIENTS_PEEPS_TOKEN
    image: ghcr.io/outsideworx/gaiapeeps:latest
    networks:
      - outsideworx
  igli:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.igli.entrypoints=websecure
        - traefik.http.routers.igli.rule=Host(`igli.info`)
        - traefik.http.routers.igli.tls.certresolver=letsencrypt
        - traefik.http.services.igli.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.igli.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.igli.loadbalancer.server.port=80
    image: ghcr.io/outsideworx/igli:latest
    networks:
      - outsideworx
  outsideworx:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.www-redirect.redirectregex.permanent=true
        - traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\.(.+)
        - traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}
        - traefik.http.routers.outsideworx.entrypoints=websecure
        - traefik.http.routers.outsideworx.middlewares=www-redirect
        - traefik.http.routers.outsideworx.rule=Host(`outsideworx.net`) || Host(`www.outsideworx.net`)
        - traefik.http.routers.outsideworx.tls.certresolver=letsencrypt
        - traefik.http.services.outsideworx.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.outsideworx.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.outsideworx.loadbalancer.server.port=80
      mode: global
    environment:
      GATE_PASSWORD: $GATE_PASSWORD_THEGREEN
      GATE_PATH: /clients/thegreen/
    image: ghcr.io/outsideworx/outsideworx:latest
    networks:
      - outsideworx
  soupart:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.soupart.entrypoints=websecure
        - traefik.http.routers.soupart.middlewares=www-redirect
        - traefik.http.routers.soupart.rule=Host(`soupart.net`) || Host(`www.soupart.net`)
        - traefik.http.routers.soupart.tls.certresolver=letsencrypt
        - traefik.http.services.soupart.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.soupart.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.soupart.loadbalancer.server.port=80
    environment:
      TOKEN: $APP_CLIENTS_SOUP_TOKEN
    image: ghcr.io/outsideworx/soupart:latest
    networks:
      - outsideworx
  soupkitchen:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.soupkitchen.entrypoints=websecure
        - traefik.http.routers.soupkitchen.middlewares=www-redirect
        - traefik.http.routers.soupkitchen.rule=Host(`soupkitchen.info`) || Host(`www.soupkitchen.info`)
        - traefik.http.routers.soupkitchen.tls.certresolver=letsencrypt
        - traefik.http.services.soupkitchen.loadbalancer.healthcheck.interval=1m
        - traefik.http.services.soupkitchen.loadbalancer.healthcheck.path=/metrics
        - traefik.http.services.soupkitchen.loadbalancer.server.port=80
    image: ghcr.io/outsideworx/soupkitchen:latest
    networks:
      - outsideworx