FROM bitnami/git AS fetcher
ARG NAME
RUN git clone --depth 1 https://github.com/outsideworx/${NAME}.git /sites
RUN git -C /sites submodule update --init --depth 1

FROM httpd:2.4
ARG NAME
ENV NAME=${NAME}
COPY --from=fetcher /sites /usr/local/apache2/htdocs/
COPY blacklist-test.conf /usr/local/apache2/conf/extra/blacklist-test.conf

RUN sed -i \
    -e 's|#LoadModule headers_module modules/mod_headers.so|LoadModule headers_module modules/mod_headers.so|' \
    -e 's|#LoadModule negotiation_module modules/mod_negotiation.so|LoadModule negotiation_module modules/mod_negotiation.so|' \
    -e 's|#LoadModule proxy_module modules/mod_proxy.so|LoadModule proxy_module modules/mod_proxy.so|' \
    -e 's|#LoadModule proxy_http_module modules/mod_proxy_http.so|LoadModule proxy_http_module modules/mod_proxy_http.so|' \
    -e 's|#LoadModule ratelimit_module modules/mod_ratelimit.so|LoadModule ratelimit_module modules/mod_ratelimit.so|' \
    -e 's|#LoadModule remoteip_module modules/mod_remoteip.so|LoadModule remoteip_module modules/mod_remoteip.so|' \
    -e 's|#LoadModule reqtimeout_module modules/mod_reqtimeout.so|LoadModule reqtimeout_module modules/mod_reqtimeout.so|' \
    -e 's|#LoadModule unique_id_module modules/mod_unique_id.so|LoadModule unique_id_module modules/mod_unique_id.so|' \
    -e '$aInclude conf/extra/blacklist-test.conf' \
    -e '$aInclude conf/extra/httpd-logs.conf' \
    -e '$aInclude conf/extra/httpd-proxy.conf' \
    -e '$aInclude conf/extra/httpd-remoteip.conf' \
    conf/httpd.conf

RUN cat <<EOF > conf/extra/httpd-remoteip.conf
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 10.0.0.0/8
RemoteIPTrustedProxy 172.16.0.0/12
RemoteIPTrustedProxy 192.168.0.0/16
EOF

RUN cat <<'EOF' > /usr/local/bin/send-to-loki.sh
#!/bin/sh
level=${1:-warn}
while read -r line; do
    timestamp=$(($(date +%s) * 1000000000))
    json="{\"streams\":[{\"stream\":{\"app\":\"${NAME}\",\"job\":\"sites\",\"level\":\"$level\"},\"values\":[[\"$timestamp\",\"$line\"]]}]}"
    curl -s -X POST -H "Content-Type: application/json" -d "$json" http://loki:3100/loki/api/v1/push
done
EOF

RUN apt update -qq && apt install -y curl; \
    chmod +x /usr/local/bin/send-to-loki.sh

RUN find conf -type f -name '*.conf' -exec sed -i -E \
    -e '/^[[:space:]]*CustomLog([[:space:]]|\\)/,/[^\\]$/d' \
    -e '/^[[:space:]]*ErrorLog/d' \
    -e '/^[[:space:]]*TransferLog/d' {} +

RUN cat <<EOF > conf/extra/httpd-logs.conf
ErrorLogFormat "%P --- ip=%a requestId=%{UNIQUE_ID}e: %M"
ErrorLog "|/usr/local/bin/send-to-loki.sh error"
LogFormat "%P --- ip=%a requestId=%{UNIQUE_ID}e: %r %>s" log_format
SetEnvIf Request_URI "^/metrics$" no_log
CustomLog "|/usr/local/bin/send-to-loki.sh info" log_format env=!no_log
EOF

RUN cat <<EOF > conf/extra/httpd-proxy.conf
ProxyRequests Off
ProxyPreserveHost On
ProxyPass        "/api/" "http://host.docker.internal:8080/api/"
ProxyPassReverse "/api/" "http://host.docker.internal:8080/api/"
<IfModule mpm_event_module>
    StartServers        1
    MinSpareThreads     4
    ThreadsPerChild     4
    MaxRequestWorkers   4
</IfModule>
<IfModule mod_ratelimit.c>
    SetOutputFilter RATE_LIMIT
    SetEnv rate-limit   640
</IfModule>
<IfModule reqtimeout_module>
    RequestReadTimeout header=2-5,MinRate=2048 body=5-30,MinRate=4096
</IfModule>
<IfModule mod_headers.c>
    RequestHeader set X-Auth-Token "test"
    RequestHeader set X-Caller-Id "${NAME}"
    RequestHeader set X-Request-Id "%{UNIQUE_ID}e"
    Header always set X-Request-Id "%{UNIQUE_ID}e"
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "DENY"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Content-Security-Policy "         \
        base-uri          'none';                       \
        connect-src       'self';                       \
        default-src       'none';                       \
        font-src            *        https:;            \
        frame-ancestors   'none';                       \
        frame-src           *        https:;            \
        form-action       'self';                       \
        img-src           'self'     data:;             \
        media-src           *        https:;            \
        script-src          *       'unsafe-inline';    \
        style-src           *       'unsafe-inline';"
</IfModule>
<IfModule mod_alias.c>
    RedirectMatch 301 ^/grafana/?$            http://localhost:8080/grafana
    RedirectMatch 301 ^/login/?$              http://localhost:8080/login
    RedirectMatch 301 ^/ntfy/?$               http://localhost:8080/ntfy
    RedirectMatch 403 /\.
    RedirectMatch 403 \.(bak|conf|config|env|ini|json|key|log|properties|php|pub|py|sh|ts|yaml|yml|zip)/?$
    RedirectMatch 403 ^(?!/(metrics|robots)\.txt$).*\.txt/?$
    RedirectMatch 403 ^(?!/(sitemap)\.xml$).*\.xml/?$
</IfModule>
<Directory "/usr/local/apache2/htdocs">
    Options +MultiViews
</Directory>
<Directory "/usr/local/apache2/htdocs/clients">
    Options +MultiViews
    DirectoryIndex index.html
</Directory>
EOF

EXPOSE 80
CMD ["httpd-foreground"]