name: Build
on:
  push:
    branches: [main]
  repository_dispatch:
    types:
      - build-come-in-and-find-out
      - build-duckumbrella
      - build-gaiapeeps
      - build-igli
      - build-outsideworx
      - build-soupart
      - build-soupkitchen
      - build-tunde-divat
jobs:
  build-sites:
    if: github.event_name == 'push'
    runs-on: self-hosted
    strategy:
      matrix:
        name:
          - come-in-and-find-out
          - duckumbrella
          - gaiapeeps
          - igli
          - outsideworx
          - soupart
          - soupkitchen
          - tunde-divat
        include:
          - name: tunde-divat
            dockerfile: Dockerfile.npm
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.DISPATCH_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v6
        with:
          build-args: NAME=${{ matrix.name }}
          context: .
          file: ${{ matrix.dockerfile || 'Dockerfile' }}
          push: true
          tags: ghcr.io/outsideworx/${{ matrix.name }}:latest
      - if: matrix.name == 'tunde-divat'
        name: Redeploy tunde-divat
        run: docker service update --force --with-registry-auth --image ghcr.io/outsideworx/tunde-divat:latest sites_tunde-divat
  build:
    if: github.event_name == 'repository_dispatch'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.DISPATCH_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v6
        with:
          build-args: NAME=${{ github.event.client_payload.name }}
          context: .
          file: ${{ contains(fromJson('["tunde-divat"]'), github.event.client_payload.name) && 'Dockerfile.npm' || 'Dockerfile' }}
          push: true
          tags: ghcr.io/outsideworx/${{ github.event.client_payload.name }}:latest
      - if: github.event.client_payload.name == 'tunde-divat'
        name: Redeploy tunde-divat
        run: docker service update --force --with-registry-auth --image ghcr.io/outsideworx/tunde-divat:latest sites_tunde-divat
